from .cli_main import build_parser
from .convert import build_simulation_spec, simulation_canonical_json, write_simulation_spec
from .manifest import (
    ConvergenceMetrics,
    M2ManifestBuilder,
    MeshStatistics,
    PortConfiguration,
    build_m2_manifest,
    load_m2_manifest,
    manifest_hash,
    validate_m2_manifest,
    write_m2_manifest,
)
from .csx_primitives import (
    BoundingBox3D,
    CSXBox,
    CSXCylinder,
    CSXGeometry,
    CSXMaterial,
    CSXMaterialType,
    CSXPolygon,
    CSXPrimitive,
    CSXPrimitiveType,
    CSXViaPad,
    NM_TO_M,
    Point3D,
    air_material,
    copper_material,
    substrate_material,
)
from .geometry import (
    BoardOutlineSpec,
    DiscontinuitySpec,
    GeometrySpec,
    LayerSpec,
    StackupSpec,
    TransmissionLineSpec,
    build_geometry_spec,
    geometry_canonical_json,
    layer_positions_nm,
    write_geometry_spec,
)
from .geometry_adapter import (
    DEFAULT_COPPER_THICKNESS_NM,
    GeometryAdapter,
    LayerZInfo,
    StackupZMap,
    build_csx_geometry,
    build_csx_geometry_from_resolved,
)
from .ports import (
    DeembedSpec,
    DeembedType,
    ImpedanceSpec,
    PortBuilder,
    PortGeometrySpec,
    PortPosition,
    PortType,
    WaveguidePortSpec,
    build_ports_from_resolved,
    waveguide_port_to_basic_port_spec,
)
from .runner import OpenEMSMode, OpenEMSRunner, parse_openems_version_output
from .sim_runner import (
    SimulationError,
    SimulationExecutionError,
    SimulationResult,
    SimulationRunner,
    SimulationSolverMode,
    SimulationTimeoutError,
    load_sparam_result,
)
from .sparam_extract import (
    ExtractionConfig,
    ExtractionResult,
    PortSignalData,
    apply_deembedding,
    build_manifest_entry,
    extract_sparams,
    extract_sparams_from_csv,
    extract_sparams_from_port_signals,
    extract_sparams_from_touchstone,
    load_port_signals_json,
    write_extraction_result,
)
from .spec import (
    SIMULATIONSPEC_SCHEMA,
    BoundarySpec,
    ConductorMaterialSpec,
    DeembedConfigSpec,
    DielectricMaterialSpec,
    EngineSpec,
    ExcitationSpec,
    FrequencySpec,
    GeometryRefSpec,
    MaterialsSpec,
    MeshResolutionSpec,
    MeshSmoothingSpec,
    MeshSpec,
    OpenEMSToolchainSpec,
    OutputSpec,
    PortSpec,
    SimulationControlSpec,
    SimulationSpec,
    TerminationSpec,
    ToolchainSpec,
    load_simulationspec,
)
from .mesh_generator import (
    MeshLineGenerator,
    RefinementZone,
    detect_antipad_refinement_zones,
    detect_trace_refinement_zones,
    detect_via_refinement_zones,
    generate_adaptive_mesh_lines,
    generate_z_mesh_lines,
    mesh_line_summary,
)
from .toolchain import DEFAULT_OPENEMS_TOOLCHAIN_PATH, OpenEMSToolchain, load_openems_toolchain
from .units import FrequencyHz, TimePS, parse_frequency_hz, parse_time_ps

__all__ = [
    # Toolchain (existing)
    "DEFAULT_OPENEMS_TOOLCHAIN_PATH",
    "BoardOutlineSpec",
    "DiscontinuitySpec",
    "GeometrySpec",
    "LayerSpec",
    "StackupSpec",
    "OpenEMSMode",
    "OpenEMSRunner",
    "OpenEMSToolchain",
    "build_parser",
    "build_geometry_spec",
    "build_simulation_spec",
    "geometry_canonical_json",
    "layer_positions_nm",
    "load_openems_toolchain",
    "parse_openems_version_output",
    # Units
    "FrequencyHz",
    "TimePS",
    "parse_frequency_hz",
    "parse_time_ps",
    # Simulation spec models
    "BoundarySpec",
    "ConductorMaterialSpec",
    "DeembedConfigSpec",
    "DielectricMaterialSpec",
    "EngineSpec",
    "ExcitationSpec",
    "FrequencySpec",
    "GeometryRefSpec",
    "MaterialsSpec",
    "MeshResolutionSpec",
    "MeshSmoothingSpec",
    "MeshSpec",
    "OpenEMSToolchainSpec",
    "OutputSpec",
    "PortSpec",
    "SimulationControlSpec",
    "SimulationSpec",
    "TransmissionLineSpec",
    "TerminationSpec",
    "ToolchainSpec",
    "SIMULATIONSPEC_SCHEMA",
    "SimulationError",
    "SimulationExecutionError",
    "SimulationResult",
    "SimulationRunner",
    "SimulationSolverMode",
    "SimulationTimeoutError",
    "load_simulationspec",
    "load_sparam_result",
    "simulation_canonical_json",
    "write_geometry_spec",
    "write_simulation_spec",
    # CSX primitives
    "BoundingBox3D",
    "CSXBox",
    "CSXCylinder",
    "CSXGeometry",
    "CSXMaterial",
    "CSXMaterialType",
    "CSXPolygon",
    "CSXPrimitive",
    "CSXPrimitiveType",
    "CSXViaPad",
    "NM_TO_M",
    "Point3D",
    "air_material",
    "copper_material",
    "substrate_material",
    # Geometry adapter
    "DEFAULT_COPPER_THICKNESS_NM",
    "GeometryAdapter",
    "LayerZInfo",
    "StackupZMap",
    "build_csx_geometry",
    "build_csx_geometry_from_resolved",
    # Mesh generator
    "MeshLineGenerator",
    "RefinementZone",
    "detect_antipad_refinement_zones",
    "detect_trace_refinement_zones",
    "detect_via_refinement_zones",
    "generate_adaptive_mesh_lines",
    "generate_z_mesh_lines",
    "mesh_line_summary",
    # Port configuration (REQ-M2-005)
    "DeembedSpec",
    "DeembedType",
    "ImpedanceSpec",
    "PortBuilder",
    "PortGeometrySpec",
    "PortPosition",
    "PortType",
    "WaveguidePortSpec",
    "build_ports_from_resolved",
    "waveguide_port_to_basic_port_spec",
    # S-parameter extraction (REQ-M2-007)
    "ExtractionConfig",
    "ExtractionResult",
    "PortSignalData",
    "apply_deembedding",
    "build_manifest_entry",
    "extract_sparams",
    "extract_sparams_from_csv",
    "extract_sparams_from_port_signals",
    "extract_sparams_from_touchstone",
    "load_port_signals_json",
    "write_extraction_result",
    # M2 Manifest generation (REQ-M2-018)
    "ConvergenceMetrics",
    "M2ManifestBuilder",
    "MeshStatistics",
    "PortConfiguration",
    "build_m2_manifest",
    "load_m2_manifest",
    "manifest_hash",
    "validate_m2_manifest",
    "write_m2_manifest",
]
