from .cli_main import build_parser
from .convert import build_simulation_spec, simulation_canonical_json, write_simulation_spec
from .csx_primitives import (
    BoundingBox3D,
    CSXBox,
    CSXCylinder,
    CSXGeometry,
    CSXMaterial,
    CSXMaterialType,
    CSXPolygon,
    CSXPrimitive,
    CSXPrimitiveType,
    CSXViaPad,
    NM_TO_M,
    Point3D,
    air_material,
    copper_material,
    substrate_material,
)
from .geometry import (
    BoardOutlineSpec,
    DiscontinuitySpec,
    GeometrySpec,
    LayerSpec,
    StackupSpec,
    TransmissionLineSpec,
    build_geometry_spec,
    geometry_canonical_json,
    layer_positions_nm,
    write_geometry_spec,
)
from .geometry_adapter import (
    DEFAULT_COPPER_THICKNESS_NM,
    GeometryAdapter,
    LayerZInfo,
    StackupZMap,
    build_csx_geometry,
    build_csx_geometry_from_resolved,
)
from .ports import (
    DeembedSpec,
    DeembedType,
    ImpedanceSpec,
    PortBuilder,
    PortGeometrySpec,
    PortPosition,
    PortType,
    WaveguidePortSpec,
    build_ports_from_resolved,
    waveguide_port_to_basic_port_spec,
)
from .runner import OpenEMSMode, OpenEMSRunner, parse_openems_version_output
from .sim_runner import SimulationResult, SimulationRunner, SimulationSolverMode
from .spec import (
    SIMULATIONSPEC_SCHEMA,
    BoundarySpec,
    ConductorMaterialSpec,
    DeembedConfigSpec,
    DielectricMaterialSpec,
    EngineSpec,
    ExcitationSpec,
    FrequencySpec,
    GeometryRefSpec,
    MaterialsSpec,
    MeshResolutionSpec,
    MeshSmoothingSpec,
    MeshSpec,
    OpenEMSToolchainSpec,
    OutputSpec,
    PortSpec,
    SimulationControlSpec,
    SimulationSpec,
    TerminationSpec,
    ToolchainSpec,
    load_simulationspec,
)
from .toolchain import DEFAULT_OPENEMS_TOOLCHAIN_PATH, OpenEMSToolchain, load_openems_toolchain
from .units import FrequencyHz, TimePS, parse_frequency_hz, parse_time_ps

__all__ = [
    # Toolchain (existing)
    "DEFAULT_OPENEMS_TOOLCHAIN_PATH",
    "BoardOutlineSpec",
    "DiscontinuitySpec",
    "GeometrySpec",
    "LayerSpec",
    "StackupSpec",
    "OpenEMSMode",
    "OpenEMSRunner",
    "OpenEMSToolchain",
    "build_parser",
    "build_geometry_spec",
    "build_simulation_spec",
    "geometry_canonical_json",
    "layer_positions_nm",
    "load_openems_toolchain",
    "parse_openems_version_output",
    # Units
    "FrequencyHz",
    "TimePS",
    "parse_frequency_hz",
    "parse_time_ps",
    # Simulation spec models
    "BoundarySpec",
    "ConductorMaterialSpec",
    "DeembedConfigSpec",
    "DielectricMaterialSpec",
    "EngineSpec",
    "ExcitationSpec",
    "FrequencySpec",
    "GeometryRefSpec",
    "MaterialsSpec",
    "MeshResolutionSpec",
    "MeshSmoothingSpec",
    "MeshSpec",
    "OpenEMSToolchainSpec",
    "OutputSpec",
    "PortSpec",
    "SimulationControlSpec",
    "SimulationSpec",
    "TransmissionLineSpec",
    "TerminationSpec",
    "ToolchainSpec",
    "SIMULATIONSPEC_SCHEMA",
    "SimulationResult",
    "SimulationRunner",
    "SimulationSolverMode",
    "load_simulationspec",
    "simulation_canonical_json",
    "write_geometry_spec",
    "write_simulation_spec",
    # CSX primitives
    "BoundingBox3D",
    "CSXBox",
    "CSXCylinder",
    "CSXGeometry",
    "CSXMaterial",
    "CSXMaterialType",
    "CSXPolygon",
    "CSXPrimitive",
    "CSXPrimitiveType",
    "CSXViaPad",
    "NM_TO_M",
    "Point3D",
    "air_material",
    "copper_material",
    "substrate_material",
    # Geometry adapter
    "DEFAULT_COPPER_THICKNESS_NM",
    "GeometryAdapter",
    "LayerZInfo",
    "StackupZMap",
    "build_csx_geometry",
    "build_csx_geometry_from_resolved",
    # Port configuration (REQ-M2-005)
    "DeembedSpec",
    "DeembedType",
    "ImpedanceSpec",
    "PortBuilder",
    "PortGeometrySpec",
    "PortPosition",
    "PortType",
    "WaveguidePortSpec",
    "build_ports_from_resolved",
    "waveguide_port_to_basic_port_spec",
]
