"""Formula Foundry M3: Artifact storage backbone.

This module provides content-addressed storage with atomic writes,
lineage tracking, and integration with DVC/MLflow tooling.
"""

from formula_foundry.m3.artifact_store import (
    ArtifactExistsError,
    ArtifactManifest,
    ArtifactNotFoundError,
    ArtifactStore,
    ArtifactStoreError,
    ContentHash,
    Lineage,
    LineageReference,
    Provenance,
    compute_spec_id,
)
from formula_foundry.m3.dataset_snapshot import (
    DatasetMember,
    DatasetNotFoundError,
    DatasetProvenance,
    DatasetSnapshot,
    DatasetSnapshotError,
    DatasetSnapshotReader,
    DatasetSnapshotWriter,
    DatasetStatistics,
    ParquetNotAvailableError,
    SplitDefinition,
    compute_manifest_hash,
)
from formula_foundry.m3.lineage_graph import (
    LineageEdge,
    LineageGraph,
    LineageGraphError,
    LineageNode,
    LineagePath,
    LineageSubgraph,
    NodeNotFoundError,
)
from formula_foundry.m3.mlflow_config import (
    M3RunContext,
    M3RunMetadata,
    M3Tracker,
    M3TrackingError,
    create_m3_run,
    get_m3_tracker,
    log_m3_artifact,
    log_m3_metric,
    log_m3_metrics,
    setup_mlflow_environment,
)
from formula_foundry.m3.registry import ArtifactRegistry

__all__ = [
    "ArtifactExistsError",
    "ArtifactManifest",
    "ArtifactNotFoundError",
    "ArtifactRegistry",
    "ArtifactStore",
    "ArtifactStoreError",
    "ContentHash",
    "DatasetMember",
    "DatasetNotFoundError",
    "DatasetProvenance",
    "DatasetSnapshot",
    "DatasetSnapshotError",
    "DatasetSnapshotReader",
    "DatasetSnapshotWriter",
    "DatasetStatistics",
    "Lineage",
    "LineageEdge",
    "LineageGraph",
    "LineageGraphError",
    "LineageNode",
    "LineagePath",
    "LineageReference",
    "LineageSubgraph",
    "M3RunContext",
    "M3RunMetadata",
    "M3Tracker",
    "M3TrackingError",
    "NodeNotFoundError",
    "ParquetNotAvailableError",
    "Provenance",
    "SplitDefinition",
    "compute_manifest_hash",
    "compute_spec_id",
    "create_m3_run",
    "get_m3_tracker",
    "log_m3_artifact",
    "log_m3_metric",
    "log_m3_metrics",
    "setup_mlflow_environment",
]
