"""Substrate utilities for deterministic, GPU-first execution."""

from . import artifact_store, backends, manifest, runner
from .artifact_store import (
    ArtifactEntry,
    ArtifactManifest,
    ArtifactManifestError,
    ArtifactStore,
    ArtifactStoreError,
    ArtifactTransaction,
)
from .backends import (
    Backend,
    BackendName,
    BackendSelectionError,
    GPUNotAvailableError,
    HostTransferError,
    cupy_to_torch,
    host_transfer_guard,
    select_backend,
    torch_to_cupy,
)
from .determinism import (
    DEFAULT_CUBLAS_WORKSPACE_CONFIG,
    VALID_CUBLAS_WORKSPACE_CONFIGS,
    DeterminismConfig,
    DeterminismMode,
    apply_determinism,
    determinism_context,
    determinism_manifest,
)
from .manifest import (
    MANIFEST_REQUIRED_FIELDS,
    Manifest,
    ManifestValidationError,
    RunArtifacts,
    build_environment_fingerprint,
    build_environment_payload,
    canonical_json_dumps,
    create_run,
    get_git_sha,
    init_run_dir,
    normalize_determinism_entry,
    sha256_bytes,
    sha256_file,
    validate_manifest,
    write_manifest,
)
from .runner import (
    DEFAULT_HARDWARE_PATH,
    DEFAULT_MEMORY_GRANULARITY_GB,
    HardwareConfig,
    LocalJobRunner,
    ResourceRequest,
    TaskSpec,
    load_hardware_config,
)

__all__ = [
    "Backend",
    "BackendName",
    "BackendSelectionError",
    "DEFAULT_CUBLAS_WORKSPACE_CONFIG",
    "GPUNotAvailableError",
    "HostTransferError",
    "VALID_CUBLAS_WORKSPACE_CONFIGS",
    "DeterminismConfig",
    "DeterminismMode",
    "ArtifactEntry",
    "ArtifactManifest",
    "ArtifactManifestError",
    "ArtifactStore",
    "ArtifactStoreError",
    "ArtifactTransaction",
    "apply_determinism",
    "artifact_store",
    "backends",
    "build_environment_fingerprint",
    "build_environment_payload",
    "canonical_json_dumps",
    "create_run",
    "cupy_to_torch",
    "determinism_context",
    "determinism_manifest",
    "host_transfer_guard",
    "select_backend",
    "get_git_sha",
    "init_run_dir",
    "MANIFEST_REQUIRED_FIELDS",
    "Manifest",
    "ManifestValidationError",
    "manifest",
    "normalize_determinism_entry",
    "DEFAULT_HARDWARE_PATH",
    "DEFAULT_MEMORY_GRANULARITY_GB",
    "HardwareConfig",
    "LocalJobRunner",
    "ResourceRequest",
    "TaskSpec",
    "RunArtifacts",
    "sha256_bytes",
    "sha256_file",
    "torch_to_cupy",
    "validate_manifest",
    "write_manifest",
    "load_hardware_config",
    "runner",
]
